### ISSUE TITLE
TASK 1: Compute candlestick data

### ISSUE THREAD

**Issue by noumanalisyed** [noumanalisyed/currency_exchange#1]
Candlesticks are a common visualization used to show the trends in a trading system. The candlesticks show what happens in a series of time windows, in terms of the starting price, the end price and the highest and lowest prices seen. The following image shows a graphical plot of candlestick data:

![image](https://github.com/noumanalisyed/currency_exchange/assets/33029215/0cbd0419-6b91-47f9-8953-81631c463865)

Figure 1: example of a graphical candlestick plot. Each box represents the trading activity in a time period. The top and bottom of a box (the candle) represent the opening and closing value of a product. The top and bottom of the lines (the candlesticks) represent the highest and lowest value seen in that time frame. The red box on May 3rd indicates the value was lower at close than open, so value went down. You do not need to make a graphical plot – you will be making a text based plot. 

In the first task, you need to compute candlestick data from the exchange data for a particular product. Here is an example of the fields needed for candlestick data:

![image](https://github.com/noumanalisyed/currency_exchange/assets/33029215/709b60e5-4b67-4210-9277-e40477bc567b)

Note that you will need to do this separately for asks and bids, and separately for different products. So the table above might be the candlestick data for ‘asks on ETH/UDST’, for example. Here is how you can compute each field: 
Open = the average price per unit in the previous time frame.
So say we want to compute the value for ETH/USDT asks from the list of items from the order book, which are all asks for ETH/USDT:

![image](https://github.com/noumanalisyed/currency_exchange/assets/33029215/643b1124-acd1-4600-b031-3d8f88c3934a)

You can see that the mean price is 6.67.
Close: the average price per unit in this time frame (same as Open, but for the current time frame)
High: highest price seen this time frame
Low: lowest price seen this time frame
You should implement the candlestick data computation using a function which returns the following data type:
std::vector<Candlestick>
Note that it returns a vector of Candlestick objects. You will need to define your own Candlestick class that is suitable for representing candlestick data. One Candlestick object represents one candlestick

**Comment by ghost** [comment]
Dear all,

We hope you are doing well.  Thank you so much for attending or viewing the recording from the mid-term webinar last Friday.

As a follow-up to the coursework discussion during the webinar, we can confirm a typo in the example when calculating the mean value in Task 1. As many of you rightly noted, the Mean Price value should be calculated by dividing the Total Value by the Total Amount (not the Total Value / Total Price). Therefore, from the example table, 20/15=1.33 (at 2 decimal places).

If you have any further questions, please ensure to get in touch via Discussion forms as soon as possible.

Best wishes,

Goldsmiths Programme Team

**Comment by noumanalisyed** [comment]
![OOP-S](https://github.com/noumanalisyed/currency_exchange/assets/33029215/b7e0473e-ddf1-46d3-b9f2-62d16021c56f)

Open, Close, High and Low Description.
